### ISSUE TITLE
Kleiner Fehler in README.md

### ISSUE THREAD

**Issue by marinesetwas** [PSteinweg/iks-coding-club-python#1]
Einen kleinen Fehler für das Aktivieren von venv im Bash-Umgebungen (Linux/Mac): Der Ordner heisst nur unter Windows `Scripts`, in anderen Betriebssystemen `bin`:

Sprich: Aus:

    source .venv/Scripts/activate

sollte

    source .venv/bin/activate

werden damit die Installation klappt.

Ich mache gerne einen Pull Request auf ;-)

**Comment by PSteinweg** [comment]
Hab die kleine Anpassung jetzt mal flott so eingepflegt, danke dir!
